name: Laravel CI
on:
  push:
    branches: [master]
      
jobs: 
  test:
    name: Laravel migrate test
    runs-on: self-hosted
    container: kudaliar032/php:7.4-cli-root
    steps:
    - uses: actions/checkout@v2
    - name: Cache PHP vendor
      uses: actions/cache@v2
      with:
        path: vendor/
        key: ${{ runner.os }}-laravel-vendor
    - name: Create .env file
      run: cp .env.testing .env
    - name: Test script
      run: |
        composer install
        php artisan config:clear
        php artisan cache:clear
        php artisan migrate
        php artisan db:seed
        php artisan test
    services:
      database:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Namex6(00)9
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: Namex6(00)9
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    needs: test
    container: kudaliar032/ansible:gpg
    steps:
    - uses: actions/checkout@v2
    - name: Decrypt deploy key
      run: ./deploy/decrypt_gpg.sh deploy/deploy_key.gpg deploy/deploy_key $DEPLOY_KEY_PASSPHRASE
    - name: Play ansible deploy playbook
      run: ansible-playbook --inventory deploy/hosts --private-key deploy/deploy_key deploy/aws.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'
