name: Laravel CI
on:
  push:
    branches: [master]
      
jobs: 
  test:
    name: Laravel migrate test
    runs-on: self-hosted
    container: kudaliar032/php:7.4-cli-root
    steps:
    - uses: actions/checkout@v2
    - name: Cache PHP vendor
      uses: actions/cache@v2
      with:
        path: vendor/
        key: ${{ runner.os }}-laravel-vendor
    - name: Create .env file
      run: cp .env.testing .env
    - name: Test script
      run: |
        composer install
        php artisan migrate
        php artisan db:seed
        php artisan test
    services:
      database:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Namex6(00)9
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: Namex6(00)9
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    needs: test
    container: dotlabs/ansible
    steps:
    - uses: actions/checkout@v2
    - name: Prepare deploy key
      run: |
        eval $(ssh-agent -s)
        /bin/bash -c 'ssh-add <(echo "$DEPLOY_KEY")'
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        ansible-playbook -i deploy/hosts deploy/aws.yml
