name: Laravel CI
on:
  push:
    branches: [master]
      
jobs: 
  test:
    name: Laravel Migrate Test
    runs-on: self-hosted
    container: kudaliar032/php:7.4-cli-root
    env:
      DB_HOST: mysql
      DB_PASSWORD: Namex6(00)9
    steps:
    - uses: actions/checkout@v2
    - name: Cache PHP vendor
      uses: actions/cache@v2
      with:
        path: vendor/
        key: ${{ runner.os }}-laravel-vendor
    - name: Create .env file
      run: cp .env.example .env
    - name: Test script
      run: |
        composer install
        php artisan migrate
        php artisan db:seed
        php artisan test
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Namex6(00)9
          MYSQL_DATABASE: laravel
